version: '3.4'

services:
  jenkins-keeper:
    image: jenkins/jenkins:lts-jdk11
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - jenkins-keeper-vol:/var/jenkins_home

volumes:
  jenkins-keeper-vol:
    driver: local